version: 1.6.0
workflows:
  - subclass: NFL
    primaryDescriptorPath: /main.nf
    readMePath: /README.md
    authors:
      - name: Mandy Sullivan
        email: xpa3@cdc.gov
        affiliation: CDC/NCIRD/ID
        orcid: '0000-0003-2007-4210'
      - name: Kristine Lacek
        email: qgx6@cdc.gov
        affiliation: CDC/NCIRD/ID
        orcid: '0000-0002-6247-5082'
      - name: Reina Chau
        email: snu3@cdc.gov
        affiliation: CDC/NCIRD/ID
        orcid: '0000-0003-3012-1404'
      - name: Sam Wiley
        email: dzw2@cdc.gov
        affiliation: CDC/NCIRD/ID
        orcid: '0009-0003-3079-5174'
      - name: Ben Rambo-Martin
        email: nbx0@cdc.gov
        affiliation: CDC/NCIRD/ID
        orcid: '0000-0002-8591-3954'
    topic: Nextflow Pipeline for Influenza, SARS-COV-2 and RSV Assembly and Curation