lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows/branch.yml
  - assets/email_template.html
  - assets/email_template.txt
  - assets/sendmail_template.txt
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
repository_type: pipeline
template:
  prefix: mira
  skip: []
