
x-base-image:
  &base-image
  python:3.10-alpine

x-pyarrow-image:
  &pyarrow-image
  python3.10-alpine:pyarrow

x-mira-nf-image:
  &mira-nf-image
  mira-nf:python3.10-alpine

x-data-volume:
  &data-volume
  type: bind
  source: /home/snu3/Github/FLU_SC2_SEQUENCING
  target: /data

services:
  pyarrow: 
    container_name: pyarrow
    image: *pyarrow-image
    build:
      context: .
      dockerfile: Dockerfile-pyarrow
      args:
        base_image: *base-image
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null

  mira-nf: 
    container_name: mira-nf
    image: *mira-nf-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        base_image: *pyarrow-image
    depends_on:
      - pyarrow
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null
