
x-python-version:
  &python-version
  python3.10

x-pyarrow-image:
  &pyarrow-image
  cdcgov/pyarrow:v17.0.0-alpine

x-mira-nf-image:
  &mira-nf-image
  mira-nf:python3.10-alpine

x-data-volume:
  &data-volume
  type: bind
  source: /home/snu3/Github/FLU_SC2_SEQUENCING
  target: /data

services:
  mira-nf: 
    container_name: mira-nf
    image: *mira-nf-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        python_image: *pyarrow-image
        python_version: *python-version
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null