version: "3.9"

x-dais-version:
  &dais-version 
  cdcgov/dais-ribosome:v1.6.1

x-irma-version:
  &irma-version 
  cdcgov/irma:v1.3.1

x-irma-core-version:
  &irma-core-version 
  ghcr.io/cdcgov/irma-core:v0.6.1

x-nextclade-version:
  &nextclade-version 
  nextstrain/nextclade:3.19.0

x-mira-oxide-version:
  &mira-oxide-version  
  cdcgov/mira-oxide:v1.4.4

x-mira-nf-version:
  &mira-nf-version  
  cdcgov/mira-nf:test

x-data-volumes:
  &data-volume
  type: bind
  source: /home/xpa3/FLU_SC2_SEQUENCING
  target: /data

x-docker-volumes:
  &docker-socket
  type: bind
  source: /var/run/docker.sock 
  target: /var/run/docker.sock 

services:
  dais: 
    container_name: dais
    image: *dais-version
    restart: always
    networks:
      - backend
    volumes: 
      - *data-volume
    command: tail -f /dev/null

  irma: 
    container_name: irma
    image: *irma-version
    restart: always
    networks:
      - backend
    volumes:
      - *data-volume
    command: tail -f /dev/null

  irma-core: 
      container_name: irma-core
      image: *irma-core-version
      restart: always
      networks:
        - backend
      volumes:
        - *data-volume
      command: tail -f /dev/null

  nextclade: 
    container_name: nextclade
    image: *nextclade-version
    restart: always
    networks:
      - backend
    volumes:
      - *data-volume
    command: tail -f /dev/null
    
  mira-oxide: 
    container_name: spyne
    image: *mira-oxide-version
    restart: always
    networks:
      - backend
    volumes:
      - *data-volume
    command: tail -f /dev/null

  mira-nf: 
    container_name: mira-nf
    image: *mira-nf-version
    depends_on:
      - dais
      - irma
      - irma-core
      - nextclade
      - mira-oxide
    restart: always
    networks:
      - frontend
      - backend
    ports: 
      - 8020:8050
    volumes:
      - *data-volume
      - *docker-socket

networks:
  backend:
    name: backend
  frontend:
    name: frontend