name: "runnextclade"
description: Run nextclade for flu, sars-cov-2 and rsv genome clade assignment
keywords:
  - nextclade
  - variant
  - consensus
  - clade
  - subclade
tools:
  - "runnextclade":
      description: genomic clade assignment, mutation calling, and sequence
        quality checks
      homepage: https://github.com/nextstrain/nextclade
      documentation: https://github.com/nextstrain/nextclade
      tool_dev_url: https://github.com/nextstrain/nextclade
      licence: ["MIT"]
      identifier: nextclade
input:
  dataset:
    - dataset_name:
        type: string
        description: |
          The name of the nextclade dataset to download.
        pattern: ".+"
    - nextclade_fasta_files:
        type: file
        description: |
          FATSA files for Nextclade analysis
        pattern: "*.fasta"
    - dataset:
        type: file
        description: |
          The nextclade dataset that was retrieved.
        pattern: "$prefix"
output:
  csv:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.csv:
        type: file
        description: CSV file containing nextclade results
        pattern: "*.{csv}"
        ontologies:
          - edam: http://edamontology.org/format_3752 # CSV
  tsv:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.tsv:
        type: file
        description: TSV file containing nextclade results
        pattern: "*.{tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3475 # TSV
  json:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.json:
        type: file
        description: JSON file containing nextclade results
        pattern: "*.{json}"
        ontologies:
          - edam: http://edamontology.org/format_3464 # JSON
  json_auspice:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.auspice.json:
        type: file
        description: Auspice JSON V2 containing nextclade results
        pattern: "*.{tree.json}"
        ontologies: []
  ndjson:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.ndjson:
        type: file
        description: newline-delimited JSON file containing nextclade results
        pattern: "*.{ndjson}"
        ontologies: []
  fasta_aligned:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.aligned.fasta:
        type: file
        description: FASTA file containing aligned sequences from nextclade results
        pattern: "*.{aligned.fasta}"
        ontologies: []
  fasta_translation:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - "*_translation.*.fasta":
        type: file
        description: FASTA file containing aligned peptides from nextclade results
        pattern: "*.{_translation.}*.{fasta}"
        ontologies: []
  nwk:
    - dataset_name:
        type: map
        description: |
          Groovy Map containing dataset information
          e.g. [ id:'test', single_end:false ]
    - ${prefix}.nwk:
        type: file
        description: NWK file containing nextclade results
        pattern: "*.{nwk}"
        ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@mandysulli"
maintainers:
  - "@mandysulli"
