name: "getnextcladedataset"
description: Get dataset for flu, sars-cov-2 and rsv genome clade assignment
keywords:
  - nextclade
  - variant
  - consensus
  - clade
  - subclade
tools:
  - "getnextcladedataset":
      description: getting database for genomic clade assignment, mutation calling, and sequence
        quality checks
      homepage: https://github.com/nextstrain/nextclade
      documentation: https://github.com/nextstrain/nextclade
      tool_dev_url: https://github.com/nextstrain/nextclade
      licence: ["MIT"]
      identifier: nextclade
input:
  database_info:
    - nextclade_fasta_files:
        type: file
        description: |
          FATSA files for Nextclade analysis
        pattern: "*.fasta"
    - dataset:
        type: string
        description: |
          The name of the nextclade dataset to download.
        pattern: ".+"
    - tag:
        type: string
        description: |
          The tag for the nextclade dataset version to download.
        pattern: ".+"
output:
  dataset:
    - dataset_name:
        type: string
        description: |
          The name of the nextclade dataset to download.
        pattern: ".+"
    - nextclade_fasta_files:
        type: file
        description: |
          FATSA files for Nextclade analysis
        pattern: "*.fasta"
    - dataset:
        type: file
        description: |
          The nextclade dataset that was retrieved.
        pattern: "$prefix"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750
authors:
  - "@mandysulli"
maintainers:
  - "@mandysulli"
