# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "nextclade"
description: A subworkflow for running Nextclade for viral sequence analysis
keywords:
  - fasta
  - nextclade
  - lineage analysis
  - sequence QC
  - viral genomics
  - phylogenetics
## TODO nf-core: Add a list of the modules and/or subworkflows used in the subworkflow
components:
  - samtools/sort
  - samtools/index
## TODO nf-core: List all of the channels used as input with a description and their structure
input:
  - summary_ch:
      type: file
      description: |
        Input channel for containing sample metadata
      pattern: "*.csv"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - nextclade_results_ch:
      type: file
      description: |
        The output channel containing the Nextclade results files
        Structure: [ val(meta), path(results) ]
      pattern: "nextclade_results/*"
authors:
  - "@mandysulli"
maintainers:
  - "@mandysulli"
